site_name: The Ironflame Guild - Docs
site_url: https://adamhstewart.github.io/doip-docs
repo_url: https://github.com/adamhstewart/doip-docs
edit_uri: edit/main/docs/
theme:
  name: material
  palette:
    primary: orange
    scheme: slate
  features:
    - content.action.edit
nav:
  - Welcome: index.md
  - Server Rules:
    - general-rules.md
    - game-rules.md
    - discord-channels.md
  - Using Avrae Commands:
    - General Information: avrae.md
    - character.md
    - saves-checks.md
    - combat.md
    - class-commands.md
  - House Rules:
    - hunting-foraging.md
    - downtime.md
    - Harvesting Monsters: harvesting.md