site_name: The Ironflame Guild - Docs
site_url: https://adamhstewart.github.io/doip-docs
repo_url: https://github.com/adamhstewart/doip-docs
edit_uri: edit/main/docs/
theme:
  name: material
  palette:
    primary: orange
    scheme: slate
  features:
    - content.action.edit
  logo: assets/images/logo.png
nav:
  - Welcome: index.md
  - Server Rules:
    - general-rules.md
    - game-rules.md
    - discord-channels.md
  - Using Avrae Commands:
    - General Information: avrae.md
    - character.md
    - saves-checks.md
    - combat.md
    - ammunition.md
    - healpot.md
    - class-commands.md
    - species-commands.md
    - currency.md
    - custom-actions.md
  - House Rules:
    - searching.md
    - combat-mechanics.md
    - hunting-foraging.md
    - downtime.md
    - bastions.md
    - Harvesting Monsters: harvesting.md
extra:
  generator: false
copyright: Copyright &copy; 2025 Ironflame Guild